// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios; // Updated to support iOS with the correct database URL
      case TargetPlatform.macOS:
        return macos; // Updated to support macOS with the correct database URL
      case TargetPlatform.windows:
        return windows; // Updated to support Windows with the correct database URL
      case TargetPlatform.linux:
        return linux; // Updated to support Linux with the correct database URL
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XGppWd3NsZTQt6HnVWXFmpSzntv2NEY',
    appId: '1:258233061657:web:0a512e41f368bce58db588',
    messagingSenderId: '258233061657',
    projectId: 'rumahsakitbab6',
    authDomain: 'rumahsakitbab6.firebaseapp.com',
    databaseURL: 'https://rumahsakitbab6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rumahsakitbab6.firebasestorage.app',
    measurementId: 'G-NG5TBW2KDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ5sYkNOrActBbWkvpWHq7GzFT-e4RnaI',
    appId: '1:258233061657:android:5d3d42b09ec5c8ab8db588',
    messagingSenderId: '258233061657',
    projectId: 'rumahsakitbab6',
    databaseURL: 'https://rumahsakitbab6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rumahsakitbab6.firebasestorage.app',
  );
  
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9XGppWd3NsZTQt6HnVWXFmpSzntv2NEY',
    appId: '1:258233061657:ios:0a512e41f368bce58db588',
    messagingSenderId: '258233061657',
    projectId: 'rumahsakitbab6',
    databaseURL: 'https://rumahsakitbab6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rumahsakitbab6.firebasestorage.app',
  );
  
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9XGppWd3NsZTQt6HnVWXFmpSzntv2NEY',
    appId: '1:258233061657:macos:0a512e41f368bce58db588',
    messagingSenderId: '258233061657',
    projectId: 'rumahsakitbab6',
    databaseURL: 'https://rumahsakitbab6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rumahsakitbab6.firebasestorage.app',
  );
  
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9XGppWd3NsZTQt6HnVWXFmpSzntv2NEY',
    appId: '1:258233061657:windows:0a512e41f368bce58db588',
    messagingSenderId: '258233061657',
    projectId: 'rumahsakitbab6',
    databaseURL: 'https://rumahsakitbab6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rumahsakitbab6.firebasestorage.app',
  );
  
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyD9XGppWd3NsZTQt6HnVWXFmpSzntv2NEY',
    appId: '1:258233061657:linux:0a512e41f368bce58db588',
    messagingSenderId: '258233061657',
    projectId: 'rumahsakitbab6',
    databaseURL: 'https://rumahsakitbab6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rumahsakitbab6.firebasestorage.app',
  );
}
